languages_list = ["python", "javascript", "html", "css", "typescript", "dockerfile", "shell", "r", "sql"]  # limited by gradio for now
topics_list = [
    "Arrays",
    "Strings",
    "Linked Lists",
    "Hash Tables",
    "Dynamic Programming",
    "Trees",
    "Graphs",
    "Sorting Algorithms",
    "Binary Search",
    "Recursion",
    "Greedy Algorithms",
    "Stack",
    "Queue",
    "Heaps",
    "Depth-First Search (DFS)",
    "Breadth-First Search (BFS)",
    "Backtracking",
    "Bit Manipulation",
    "Binary Search Trees",
    "Tries",
    "Union Find",
    "Geometry",
    "Segment Trees",
    "Game Theory",
    "Topological Sort",
    "Fenwick Tree",
    "Number Theory",
    "Sliding Window",
    "Disjoint Set",
    "Hashing",
    "Probabilities",
    "Combinatorics",
    "Minimax",
    "Two Pointers",
    "Suffix Array",
    "Fast Fourier Transform",
    "Matrix Operations",
    "Eulerian Path",
    "Bellman-Ford Algorithm",
    "Floyd-Warshall Algorithm",
    "Prim's Algorithm",
    "Kruskal's Algorithm",
    "Rabin-Karp Algorithm",
    "Z-algorithm",
    "Manacher's Algorithm",
    "AVL Trees",
    "Red-Black Trees",
    "Splay Trees",
    "Treaps",
    "Computational Geometry",
]
models = ["gpt-3.5-turbo"]
