interview_types = ["coding", "ml_design", "ml_theory", "system_design", "math", "sql", "custom"]

topic_lists = {
    "coding": [
        "Arrays",
        "Strings",
        "Linked Lists",
        "Hash Tables",
        "Dynamic Programming",
        "Trees",
        "Graphs",
        "Sorting Algorithms",
        "Binary Search",
        "Recursion",
        "Greedy Algorithms",
        "Stack",
        "Queue",
        "Heaps",
        "Depth-First Search (DFS)",
        "Breadth-First Search (BFS)",
        "Backtracking",
        "Bit Manipulation",
        "Binary Search Trees",
        "Tries",
    ],
    "system_design": [
        "Machine Learning Systems",
        "Databases",
        "Mobile Application Architecture",
        "Web Services and APIs",
        "Cloud Computing and Storage",
        "Network Architecture and Protocols",
        "Security and Compliance",
        "Distributed Systems",
        "Real-time and Batch Processing",
        "Content Delivery Networks",
    ],
    "ml_design": [
        "Computer Vision",
        "Natural Language Processing",
        "Recommendation Engines",
        "Predictive Maintenance",
        "Fraud Detection",
        "Autonomous Driving",
        "Retail Analytics",
        "Speech Recognition",
        "Customer Segmentation",
        "Real-Time Bidding",
        "Supply Chain Optimization",
        "Video Analysis",
        "Personalized Advertising",
    ],
    "math": [
        "Probability Theory",
        "Statistical Distributions",
        "Hypothesis Testing",
        "Linear Algebra",
        "Calculus",
        "Discrete Mathematics",
        "Optimization Techniques",
        "Bayesian Statistics",
        "Regression Analysis",
        "Combinatorics",
        "Graph Theory",
        "Game Theory",
        "Numerical Methods",
        "Logic Puzzles",
        "Complexity Theory",
        "Fourier Analysis",
    ],
    "sql": [
        "Basic SQL Queries",
        "Complex Joins",
        "Subqueries",
        "Aggregation and Grouping",
        "Window Functions",
        "Indexing and Performance Tuning",
        "SQL Functions",
        "Stored Procedures",
        "Trigger and Events",
        "Database Design",
        "Normalization",
        "Concurrency Control",
        "Transaction Management",
        "Backup and Recovery",
        "Security in SQL",
        "Data Import/Export",
        "NoSQL vs SQL",
        "Data Warehousing",
        "SQL in Big Data Analytics",
    ],
    "ml_theory": [
        "Supervised Learning",
        "Unsupervised Learning",
        "Reinforcement Learning",
        "Deep Learning",
        "Feature Engineering",
        "Model Evaluation Metrics",
        "Bias-Variance Tradeoff",
        "Ensemble Methods",
        "Neural Networks Architecture",
        "Convolutional Neural Networks",
        "Recurrent Neural Networks",
        "Dimensionality Reduction",
        "Large Language Models",
        "Transformers",
        "Diffusion Models",
        "Clustering Algorithms",
        "Gradient Descent",
        "Regularization Techniques",
        "Loss Functions",
        "Optimization Algorithms",
        "Generative Adversarial Networks",
        "Transfer Learning",
        "Explainable AI",
    ],
    "custom": [
        "Specify any topic",
    ],
}

fixed_messages = {
    "intro": "Nice to meet you! I'm your AI interviewer. Click 'Generate a problem' to start.",
    "start": "Nice to meet you! I'm your AI interviewer. Read the problem statement, share your initial thoughts or ask questions using the record button.",
    "end": "The interview is complete. Thank you! Feedback will follow shortly.",
    "error": "An error occurred. Please try again.",
}
