topic_lists = {
    "coding": [
        "Arrays",
        "Strings",
        "Linked Lists",
        "Hash Tables",
        "Dynamic Programming",
        "Trees",
        "Graphs",
        "Sorting Algorithms",
        "Binary Search",
        "Recursion",
        "Greedy Algorithms",
        "Stack",
        "Queue",
        "Heaps",
        "Depth-First Search (DFS)",
        "Breadth-First Search (BFS)",
        "Backtracking",
        "Bit Manipulation",
        "Binary Search Trees",
        "Tries",
    ],
    "system_design": [
        "Machine Learning Systems",
        "Databases",
        "Mobile Application Architecture",
        "Web Services and APIs",
        "Cloud Computing and Storage",
        "Network Architecture and Protocols",
        "Security and Compliance",
        "Distributed Systems",
        "Real-time and Batch Processing",
        "Content Delivery Networks",
    ],
}

fixed_messages = {
    "intro": "Nice to meet you! I'm your AI interviewer. Click 'Generate a problem' to start.",
    "start": "Read the problem statement, share your initial thoughts, and ask questions using the record button.",
    "end": "The interview is complete. Thank you! Feedback will follow shortly.",
    "error": "An error occurred. Please try again.",
}
